### ISSUE TITLE
Single quote on Turtle

### ISSUE THREAD

**Issue by FerrariAndrea** [filip26/titanium-json-ld#181]
Hi,

**Describe the bug**
Seems that Titanium lib can't recognize singles quotes in the literals of turtle RDF format.
I need to use singles quotes `'` on my RDF turtle and then convert it in json-ld.
Here you can find all types of quotes accepted from RDF-turtle:
[Turtle literals quote](https://www.w3.org/TR/turtle/#turtle-literals)

I get this error:
```
Caused by: com.apicatalog.rdf.io.error.RdfReaderException: Unexpected character ['] expected [\t, \n, \r, ^, @, SPACE, ., <, _, ", #].
	at com.apicatalog.rdf.io.nquad.Tokenizer.unexpected(Tokenizer.java:133)
	at com.apicatalog.rdf.io.nquad.Tokenizer.doRead(Tokenizer.java:120)
	at com.apicatalog.rdf.io.nquad.Tokenizer.next(Tokenizer.java:50)
	at com.apicatalog.rdf.io.nquad.Tokenizer.accept(Tokenizer.java:61)
	at com.apicatalog.rdf.io.nquad.NQuadsReader.skipWhitespace(NQuadsReader.java:235)
	at com.apicatalog.rdf.io.nquad.NQuadsReader.reaStatement(NQuadsReader.java:83)
	at com.apicatalog.rdf.io.nquad.NQuadsReader.readDataset(NQuadsReader.java:69)
	at com.apicatalog.jsonld.document.RdfDocument.of(RdfDocument.java:119)
	... 26 more
```

**To Reproduce**
```
String turtle = "<http://this.is.a.test_e5a8> <https://uri.etsi.org/ngsi-ld/coordinates> '1.33903E1'.\n"
+ "<http://this.is.a.test_9d6b> <https://uri.etsi.org/ngsi-ld/coordinates> '5.25075E1'.";

JsonArray json_ld =  super.rdfToJsonLd(turtle);
```

**Expected behavior**
Maybe you can allow singles quotes too.

**Additional context**
I m use Titanium to convert JSON-LD to RDF and vice versa, but sometimes I need to add manual RDF triples that can contain double quotes `"` inside a literal, so I need to use singles quotes. 

Thank you.

**Comment by filip26** [comment]
Hi,
thank you for reporting the issue. Unfortunately, Turtle format is not supported now, only N-Quads/Triples

**Comment by FerrariAndrea** [comment]
Hi,
yea, sorry, in my case N-Quads or Turtle it's not important, I just need to use `'` instead `"` for literals.
I look N-Quads standard right now, and I confirm that they use only `"`, so maybe you should implement directly Turtle format instead of add `'` to N-Quads (which would not respect the standard).

Thank you

**Comment by filip26** [comment]
closed due inactivity, feel free to re-open with new information.
