### ISSUE TITLE
java.io.IOException: Too many open files in system when running tests

### ISSUE THREAD

**Issue by kevinpeterson** [filip26/titanium-json-ld#33]
Hello,

I'm getting the following error when running the tests:

```
java.lang.InternalError: java.io.IOException: Too many open files in system
	at java.net.http/jdk.internal.net.http.HttpClientImpl.<init>(HttpClientImpl.java:311)
	at java.net.http/jdk.internal.net.http.HttpClientImpl.create(HttpClientImpl.java:253)
	at java.net.http/jdk.internal.net.http.HttpClientBuilderImpl.build(HttpClientBuilderImpl.java:135)
	at com.apicatalog.jsonld.loader.HttpLoader.<init>(HttpLoader.java:38)
	at com.apicatalog.jsonld.api.JsonLdOptions.<init>(JsonLdOptions.java:88)
	at com.apicatalog.jsonld.suite.JsonLdTestCase.getOptions(JsonLdTestCase.java:154)
	at com.apicatalog.jsonld.JsonLdToRdfTest.testToRdf(JsonLdToRdfTest.java:62)
       .....
```

I believe ```com.apicatalog.jsonld.loader.HttpLoader``` is building a new ```java.net.http.HttpClient``` for each instance -- is that necessary, or can one instance of the ```HttpClient``` be reused?

**Comment by filip26** [comment]
Hi,
only remote tests (~38 files) use `HttpLoader` and `WireMock` to test remote document and context retrieval. The instance of `HttpLoader` should be shared here. Good point! The other tests use custom loader loading test files from zip file. 

I would be glad if you can help me investigate this. 

Thank you

**Comment by filip26** [comment]
Please, try latest version. Yesterday, a bug causing resource leak in `HttpLoader` has been fixed. [details here](https://lgtm.com/projects/g/filip26/titanium-json-ld/rev/pr-89e2776f4b4334fe28ee1c07ae2479c24aebd98d)
